### ISSUE TITLE
#1A Implement a Typography-component

### ISSUE THREAD

**Issue by UrsulaMontag** [UrsulaMontag/capstone-project#10]

**Comment by UrsulaMontag** [comment]
# Value Proposition

**As a** developer
**I need** a styled Typography component
**to be able to** represent different typo-styles in a clear and reusable way 

# Description

For clear and reusable styling of the typography elements in my app, I need the typography component that renders the respective styling. 

# Acceptance Criteria

- [ ] All typos are reusable


# Tasks


- [ ] Create a new branch typography
- [ ] Create a new component, that renders styling for the used typography elements in the project
- [ ] For the beginning the component renders the main typography-elements that are needed to enable basic styling, like StyledH* and StyledP
- [ ] Exchange the previously rendered typo-elements for the created styled elements

# Complexity
S
