### ISSUE TITLE
#2 List entries

### ISSUE THREAD

**Issue by UrsulaMontag** [UrsulaMontag/capstone-project#4]

**Comment by UrsulaMontag** [comment]
**As a conservationist
**I need a list of all of my entries
**to be able to get a better overview  about past entries

# Description
![userstory#2](https://user-images.githubusercontent.com/101577550/167258166-c249feb3-a8f7-4687-b35a-bebdc6adc789.png)



# Acceptance Criteria

- [ ] Each entry should be visually separated
- [ ] Each entry should be displayed with the important details (see #3 )
- [ ] All available entries should be displayed


# Tasks


- [ ] Create a data structure to hold an array of multiple products
- [ ] Create a component to render the list of products
- [ ] The component receives the array via props
- [ ] Add a test to check if all given entries are rendered
- [ ] Add component to index page
- [ ] Add to storybook
- [ ] Add basic styling

# Complexity
S

**Comment by UrsulaMontag** [comment]
Hey Anita, 
thanks for your feedback. I hope the tasks are detailed enough now.

**Comment by mbosselmann** [comment]
Hi Ursula,
I like your user story and I have nothing else to remark about the content. :) Only one minor styling tip in your value proposition: If you want to have a bold text you need to add `**` before and after the selected part like `**As a**`. Maybe this is interesting for you. :)

**Comment by UrsulaMontag** [comment]
Thank you!
