### ISSUE TITLE
#3 Display entries on a map

### ISSUE THREAD

**Issue by UrsulaMontag** [UrsulaMontag/capstone-project#5]

**Comment by UrsulaMontag** [comment]
# Value Proposition

**As a conservationist 
**I need a map
**to be able to see and search my environment

# Description
![userstory#3](https://user-images.githubusercontent.com/101577550/167394251-ab4b3328-dbe6-4777-aae0-def09bca3036.png)


# Acceptance Criteria

- [ ] The map  data comes from leaflet.js library
- [ ] The maps size has to be set 
- [ ] Make sure, the map shows content

# Tasks

- [ ] Create a new branch "leaflet-map"
- [ ] Install required dependencies
- [ ] Create a component to render the map
- [ ] Add a MapContainer (import from 'react-leaflet')
- [ ] Use basic attributes for MapContainer from react-leaflet to initialize the map (center, zoom, scrollWheelZoom, position) and prevent a default gray map-window
- [ ] Add a tylelayer with url and attribution to OpenStreetMap
- [ ] Write test to check map-rendering
- [ ] Add to storybook
- [ ] Add map component to app
- [ ]  Make sure, you prevent ssr by dynamic import 



# Complexity
M

**Comment by HishamAlmannai** [comment]
I think the acceptance criteria is a bit fuzzy. Is the map already interactive?  Maybe you could link the User Story #5 to it. So it is clear that any content is sufficient. 

Does the specific map-library not belong to the technical issues/Tasks? "Existing Map-data should be used" 

Maybe something like: "The map size has to be set to a appropriate static size."
Or should it be responsive already?

**Comment by UrsulaMontag** [comment]
Hey Hisham,
thank you for your helpful comment. hopefully i have understood and implemented your objections correctly.

**Comment by FranziGraml** [comment]
Hi Ursula,
I like your story!
You have implemented the comments very well. good job.... happy coding :)
