### ISSUE TITLE
#4 Center map to current location

### ISSUE THREAD

**Issue by UrsulaMontag** [UrsulaMontag/capstone-project#6]

**Comment by UrsulaMontag** [comment]
# Value Proposition

**As a natureobserver
**I need to see the map centered to my current position
**to be able to easily get around in my environment

# Description

the map created before (see #5 ) has to be centered to current user-location

# Acceptance Criteria

- [ ] When the map is rendered, it shows the current location 
- [ ] Location data are available from browser-data
- [ ] The user is asked if location-data is shared
- [ ] The map should be centered by default, if current location-data is not available
- [ ] An error-message is displayed, when browser or location-data not available
- [ ] State-handling with zustand

# Tasks

(for developers team)

- [ ] Create a new branch map-center
- [ ] Create a new file useStore
- [ ] Create state for current location
- [ ] Create function to handle state and set current location
- [ ] Inside your app take useEffect to call state-handle-function
- [ ] Implement state to center-attribute in MapContainer
- [ ] Write a test that checks if data receives from browser
- [ ] Write a test that checks if default-centering is shown correct
- [ ] Write a test, that checks if current-location is shown correct

# Complexity
M

**Comment by irenepapaspyratos** [comment]
Looks fine to me. 😊
