### ISSUE TITLE
#2 Display location of a single entry

### ISSUE THREAD

**Issue by UrsulaMontag** [UrsulaMontag/capstone-project#7]

**Comment by UrsulaMontag** [comment]
# Value Proposition

**As a natureobserver
**I need to see the previously made entries
**to be able to remember, compare and monitor the entries of my particular nature observations

# Description

![userstory#1](https://user-images.githubusercontent.com/101577550/167575963-afc41a70-aba1-4948-9f3a-284282de7c35.png)



# Acceptance Criteria

- [ ] Direktly below the entries name, the entries place is displayed by longitude and latitude, titeled by "Place:"
- [ ] The entries longitude is displayed, labeled by "Long:"
- [ ] The entries latitude is displayed, labeled by "Lat:"

# Tasks

- [ ] Create a new branch "display-location-entry"
- [ ] Create data-structure to hold the entry-location
- [ ] Render the data in the previously created component (see #3 )
- [ ] The component receives the entry-location via props
- [ ] Add test to check if data is rendered 

# Complexity
S
